let data_product =[
    {id: 1, name: "Men's Casual Shirt", category: "Men", image: "/images/men/1.jpg", new_price: 1999, old_price: 2699},
    {id: 2, name: "Men's Denim Jeans", category: "Men", image: "/images/men/2.jpg", new_price: 2699, old_price: 3499},
    {id: 3, name: "Men's Sports Shoes", category: "Men", image: "/images/men/3.jpg", new_price: 3999, old_price: 4999},
    {id: 4, name: "Men's Leather Jacket", category: "Men", image: "/images/men/4.jpg", new_price: 5999, old_price: 6999},
    {id: 5, name: "Men's Formal Tie", category: "Men", image: "/images/men/5.jpg", new_price: 999, old_price: 1399},
    {id: 6, name: "Men's Backpack", category: "Men", image: "/images/men/6.jpg", new_price: 1499, old_price: 1899},
    {id: 7, name: "Men's Polo Shirt", category: "Men", image: "/images/men/7.jpg", new_price: 1299, old_price: 1599},
    {id: 8, name: "Men's Dress Shoes", category: "Men", image: "/images/men/8.jpg", new_price: 3499, old_price: 4199},
    {id: 9, name: "Men's Winter Coat", category: "Men", image: "/images/men/9.jpg", new_price: 4999, old_price: 6999},
    {id: 10, name: "Men's Sunglasses", category: "Men", image: "/images/men/10.jpg", new_price: 1999, old_price: 2699},
    {id: 11, name: "Men's Running Shorts", category: "Men", image: "/images/men/11.jpg", new_price: 999, old_price: 1399},
    {id: 12, name: "Men's Graphic T-Shirt", category: "Men", image: "/images/men/12.jpg", new_price: 1199, old_price: 1599},
    {id: 13, name: "Men's Cargo Pants", category: "Men", image: "/images/men/13.jpg", new_price: 2799, old_price: 3499},
    {id: 14, name: "Men's Beanie Hat", category: "Men", image: "/images/men/14.jpg", new_price: 599, old_price: 799},
    {id: 15, name: "Men's Hooded Sweatshirt", category: "Men", image: "/images/men/15.jpg", new_price: 1899, old_price: 2499},
    {id: 16, name: "Men's Tech Backpack", category: "Men", image: "/images/men/16.jpg", new_price: 3499, old_price: 4199},
    {id: 17, name: "Men's Wrist Watch", category: "Men", image: "/images/men/17.jpg", new_price: 2699, old_price: 3499},
    {id: 18, name: "Men's Athletic Shorts", category: "Men", image: "/images/men/18.jpg", new_price: 1299, old_price: 1599},
    {id: 19, name: "Women's Casual Dress", category: "Women", image: "/women_images/1.jpg",new_price: 2199,old_price: 2899},
    {id: 20, name: "Women's Skinny Jeans", category: "Women", image: "/women_images/2.jpg", new_price: 2899, old_price: 3699},
    {id: 21, name: "Women's Heeled Shoes", category: "Women", image: "/women_images/3.jpg", new_price: 3999, old_price: 4999},
    {id: 22, name: "Women's Leather Jacket", category: "Women", image: "/women_images/4.jpg", new_price: 6299, old_price: 7299},
    {id: 23, name: "Women's Elegant Blouse", category: "Women", image: "/women_images/5.jpg", new_price: 1199, old_price: 1499},
    {id: 24, name: "Women's Handbag", category: "Women", image: "/women_images/6.jpg", new_price: 1599, old_price: 1999},
    {id: 25, name: "Women's Floral Dress", category: "Women", image: "/women_images/7.jpg", new_price: 1499, old_price: 1899},
    {id: 26, name: "Women's High Heels", category: "Women", image: "/women_images/8.jpg", new_price: 3799, old_price: 4499},
    {id: 27, name: "Women's Winter Coat", category: "Women", image: "/women_images/9.jpg", new_price: 5599, old_price: 6999},
    {id: 28, name: "Women's Sunglasses", category: "Women", image: "/women_images/10.jpg", new_price: 1899, old_price: 2499},
    {id: 29, name: "Women's Running Shorts", category: "Women", image: "/women_images/11.jpg", new_price: 1199, old_price: 1599},
    {id: 30, name: "Women's Graphic T-Shirt", category: "Women", image: "/women_images/12.jpg", new_price: 1399, old_price: 1799},
    {id: 31, name: "Women's Wide Leg Pants", category: "Women", image: "/women_images/13.jpg", new_price: 2999, old_price: 3599},
    {id: 32, name: "Women's Beret Hat", category: "Women", image: "/women_images/14.jpg", new_price: 799, old_price: 999},
    {id: 33, name: "Women's Hooded Sweatshirt", category: "Women", image: "/women_images/15.jpg", new_price: 2099, old_price: 2799},
    {id: 34, name: "Women's Backpack", category: "Women", image: "/women_images/16.jpg", new_price: 3599, old_price: 4299},
    {id: 35, name: "Women's Wrist Watch", category: "Women", image: "/women_images/17.jpg", new_price: 2899, old_price: 3599},
    {id: 36, name: "Women's Activewear Shorts", category: "Women", image: "/women_images/18.jpg", new_price: 1299, old_price: 1599},
    {id: 37, name: "Kids' Cartoon Print T-shirt", category: "Kids", image: "/images/kids/1.jpg", new_price: 799, old_price: 999},
    {id: 38, name: "Kids' Denim Shorts", category: "Kids", image: "/images/kids/2.jpg", new_price: 899, old_price: 1199},
    {id: 39, name: "Girls' Floral Print Dress", category: "Kids", image: "/images/kids/3.jpg", new_price: 1299, old_price: 1499},
    {id: 40, name: "Boys' Striped Polo Shirt", category: "Kids", image: "/images/kids/4.jpg", new_price: 699, old_price: 899},
    {id: 41, name: "Kids' Jogger Pants", category: "Kids", image: "/images/kids/5.jpg", new_price: 1099, old_price: 1399},
    {id: 42, name: "Girls' Denim Overall Dress", category: "Kids", image: "/images/kids/6.jpg", new_price: 1499, old_price: 1799},
    {id: 43, name: "Boys' Graphic Print Hoodie", category: "Kids", image: "/images/kids/7.jpg", new_price: 1199, old_price: 1499},
    {id: 44, name: "Kids' Rainbow Striped Leggings", category: "Kids", image: "/images/kids/8.jpg", new_price: 699, old_price: 899},
    {id: 45, name: "Girls' Unicorn Print Pajamas", category: "Kids", image: "/images/kids/9.jpg", new_price: 999, old_price: 1299},
    {id: 46, name: "Boys' Camouflage Print Cargo Shorts", category: "Kids", image: "/images/kids/10.jpg", new_price: 1099, old_price: 1399},
    {id: 47, name: "Kids' Striped Long Sleeve Shirt", category: "Kids", image: "/images/kids/11.jpg", new_price: 799, old_price: 999},
    {id: 48, name: "Girls' Ruffled Skirt", category: "Kids", image: "/images/kids/12.jpg", new_price: 899, old_price: 1199},
    {id: 49, name: "Boys' Checkered Shirt", category: "Kids", image: "/images/kids/13.jpg", new_price: 799, old_price: 999},
    {id: 50, name: "Kids' Unicorn Print Onesie", category: "Kids", image: "/images/kids/14.jpg", new_price: 1299, old_price: 1499},
    {id: 51, name: "Girls' Floral Print Skater Dress", category: "Kids", image: "/images/kids/15.jpg", new_price: 1399, old_price: 1699},
    {id: 52, name: "Boys' Cargo Jogger Pants", category: "Kids", image: "/images/kids/16.jpg", new_price: 1099, old_price: 1399},
    {id: 53, name: "Kids' Rainbow Striped Sweater", category: "Kids", image: "/images/kids/17.jpg", new_price: 1199, old_price: 1499},
    {id: 54, name: "Girls' Polka Dot Blouse", category: "Kids", image: "/images/kids/18.jpg", new_price: 899, old_price: 1199}
  ]

  export default data_product